server:
  port: 8000
  servlet:
    contextPath: /api
  error:
    include-stacktrace: never
    
spring:
   application:
      name: api
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
   jpa:
      database-platform:
         org.hibernate.dialect.H2Dialect
   h2:
      console:
         enabled: true
   security:
      user: 
         name: username
         password: password
         
springdoc:
   api-docs:
      path: /api-docs
         